---
title: "midtermwork003"
author: "林舜禾"
date: "2017年2月10日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r  message=FALSE}
library(plotly)
```

#散布圖
```{r}
library(ggplot2)
ggplotly(
  ggplot(cars, aes(x = speed, y = dist))+
  geom_point() +  #散布圖
  ggtitle("Car speed vs. braking distance") +
  xlab("Speed") +
  ylab("Dist") +
  geom_smooth(method = "lm") 
  )
```

#線圖
```{r}
ggplotly(
  ggplot(economics, aes(x = date, y = unemploy/pop)) + 
  geom_line()
  )
```

#直方圖
```{r}
ggplotly(
  ggplot(iris, aes(x = Sepal.Length)) +
  geom_histogram(binwidth=0.6) + 
  facet_wrap(~ Species)  #用每種各畫一個 加入 ncol = 1 垂直展開
)
```

#盒鬚圖
```{r}
ggplotly(
  ggplot(iris, aes(x = "", y = Sepal.Length)) +
  geom_boxplot()+
    xlab("Boxplot")
)
```

#長條圖
```{r}
ggplotly(
  ggplot(mtcars, aes(x = row.names(mtcars), y = hp)) +
  geom_bar(stat = "identity") + #stat = "identity" 可以呈現數值 
  coord_flip() #xy反轉
)
ggplotly(
  ggplot(mpg, aes(x = class)) + 
  geom_bar(aes(fill = drv)) #aes(fill = drv) 納入類別變數的顏色
)
ggplotly(
  ggplot(mpg, aes(x = class)) +
  geom_bar(aes(fill = drv), position = "dodge") #改成非累積圖
)

ggplotly(
  ggplot(mpg, aes(x = class)) +
  geom_bar(aes(fill = drv), position = "fill") + #改成比率圖
  ylab("Percentage")
)
```